const imagePaths = {
    Home: require('../assets/images/bottomTabImages/Home.png'),
    Bookings: require('../assets/images/bottomTabImages/Bookings.png'),
    Dashboard: require('../assets/images/bottomTabImages/Dashboard.png'),
    Favorites: require('../assets/images/bottomTabImages/Favorites.png'),
    Profile: require('../assets/images/bottomTabImages/Profile.png'),
    LoginBg: require('../assets/images/bgImages/login.png'),
    SignupBg: require('../assets/images/bgImages/signup.png'),
    Google: require('../assets/images/socialIcons/Google.png'),
    Apple: require('../assets/images/socialIcons/Apple.png'),
    Facebook: require('../assets/images/socialIcons/Facebook.png'),
    logo: require('../assets/images/logoo.png'),
    backArrow: require('../assets/images/backArrow.png'),
    Search: require('../assets/images/searchNew.png'),
    StudioPlaceHolderImage: require('../assets/images/studio_placeholder.png'),
    Splash: require('../assets/images/Splash_Screen.png'),
    Location: require('../assets/images/location.png'),
    SquareFt: require('../assets/images/SquareFt.png'),
    Heart: require('../assets/images/heart.png'),
    HeartSelected: require('../assets/images/HeartSelected.png'),
    rightArrow: require('../assets/images/rightArrow.png'),
    PhotographerPlaceHolderImage: require('../assets/images/photographer_placeholder.jpg'),
    LocationNew: require('../assets/images/LocationNew.png'),
    NotificationNew: require('../assets/images/NotificationNew.png'),
    camera: require('../assets/images/whyChoose/camera.png'),
    thunder: require('../assets/images/whyChoose/thunder.png'),
    payment: require('../assets/images/whyChoose/payment.png'),
    star: require('../assets/images/whyChoose/star.png'),
    target: require('../assets/images/whyChoose/target.png'),
    mobile: require('../assets/images/whyChoose/mobile.png'),
};

export default imagePaths;